# Generated by Django 5.1.2 on 2024-12-10 21:15

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_gamesession_last_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsession',
            name='uid_for_session',
        ),
        migrations.AddField(
            model_name='loginsession',
            name='user_id',
            field=models.CharField(db_default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 10, 21, 15, 12, 837753)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_session_id',
            field=models.CharField(db_default=uuid.UUID('1efb73bd-81c3-6931-93f5-7cafc45dc594'), max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 10, 21, 15, 12, 845685), verbose_name='last activity'),
        ),
    ]
