# Generated by Django 5.1.2 on 2024-12-10 21:25

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0006_remove_loginsession_uid_for_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 10, 21, 25, 39, 572542)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_session_id',
            field=models.CharField(db_default=uuid.UUID('1efb73d4-dac5-6e12-b376-c391c96f09ad'), max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 10, 21, 25, 39, 580507), verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 10, 21, 25, 39, 580871), verbose_name='date time deleted'),
        ),
    ]
