# Generated by Django 5.1.2 on 2024-12-11 17:12

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0007_alter_accountinfo_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='game_session_json',
        ),
        migrations.RemoveField(
            model_name='loginsession',
            name='date_created',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='date_time_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262271), verbose_name='date time created'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='date_time_ended',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262277), verbose_name='date time ended'),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='date_time_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262534), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 254738)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262250), verbose_name='date time deleted'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_session_id',
            field=models.CharField(db_default=uuid.UUID('1efb7e32-7a90-6517-8ad3-c6460f24e373'), max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262261), verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='last_player',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262546), verbose_name='date time deleted'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='last_activity_tracker',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 11, 17, 12, 52, 262524), verbose_name=' last activity'),
        ),
    ]
