# Generated by Django 5.1.2 on 2024-12-14 14:55

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0008_remove_gamesession_game_session_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player_login_session',
            field=models.CharField(db_default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 713580)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721175), verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721154), verbose_name='date time deleted'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_ended',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721181), verbose_name='date time ended'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_session_id',
            field=models.CharField(db_default=uuid.UUID('1efba2b7-4c52-6242-9d5d-22218f5be599'), max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721168), verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='date_time_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721444), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721450), verbose_name='date time deleted'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='last_activity_tracker',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 14, 14, 55, 27, 721436), verbose_name=' last activity'),
        ),
    ]
