# Generated by Django 5.1.2 on 2024-12-16 17:42

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0010_alter_accountinfo_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='game_board',
            new_name='game_pieces',
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='date_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 254761)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262363), verbose_name='date time created'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262344), verbose_name='date time deleted'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_time_ended',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262369), verbose_name='date time ended'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_session_id',
            field=models.CharField(db_default=uuid.UUID('1efbbd52-4dc5-681c-aaa5-31a9d620c9de'), max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='last_activity',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262356), verbose_name='last activity'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='date_time_created',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262623), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='date_time_deleted',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262630), verbose_name='date time deleted'),
        ),
        migrations.AlterField(
            model_name='loginsession',
            name='last_activity_tracker',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 12, 16, 17, 42, 39, 262613), verbose_name=' last activity'),
        ),
    ]
